name: Deploy to EC2

on:
  push:
    paths:
      - "server/**"
    branches:
      - "main"

env:
  PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
  EC2_INSTANCE: ${{secrets.EC2_INSTANCE}}

jobs:
  deploy_to_ec2:
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Store Private key to a PEM file
        run: |-
          echo  ${{env.PRIVATE_KEY}} > chat-up.pem
          chmod 600 chat-up.pem

      - name: Push files to EC2 instance
        run: |-
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env'
          -e "ssh -i chat-up.pem" 
          ./server ${{env.EC2_INSTANCE}}:~/app

      - name: SSH to EC2 instance and restart server
        run: |-
          ssh -i "chat-up.pem" ${{env.EC2_INSTANCE}}
          pm2 restart chatup-server
          exit
