import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ShadCNThemeProvider from "@/components/ShadCnThemeProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import NextAuthSessionProvider from "@/components/NextAuthSessionProvider";
import ReduxProvider from "@/components/ReduxProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Croom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("flex w-screen h-screen max-h-screen", poppins.className)}
      >
        <ReduxProvider>
          <ShadCNThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
            <Toaster />
          </ShadCNThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
