import "dotenv/config";
import { createTransport } from "nodemailer";
import { render } from "@react-email/components";
import JSONResponse from "../../lib/json-response";
import { FastifyInstance, FastifyPluginOptions } from "fastify";
import OTP from "../../database/models/Otp";
import User from "../../database/models/User";
import SignUpEmail from "../../lib/email/SignUpEmail";
import RecoverEmail from "../../lib/email/RecoverEmail";
import { ClientSession, startSession } from "mongoose";

export default function v1OTPRouter(fastify: FastifyInstance, _: FastifyPluginOptions, done: () => void) {
  const gmail_user = process.env.GMAIL_USER;
  if (!gmail_user) throw new Error("GMAIL_USER is missing from your .env file \n GMAIL_USER is your gmail address");

  const gmail_password = process.env.GMAIL_2F_AUTH_APP_PASS;
  if (!gmail_password)
    throw new Error(
      `GMAIL_2F_AUTH_APP_PASS is missing from your .env file 
        \n  GMAIL_2F_AUTH_APP_PASS is the password generated by GOOGLE App Password \n see
        {(https://myaccount.google.com/u/2/apppasswords?continue=https://myaccount.google.com/u/2/?
        hl%3Den%26utm_source%3DOGB%26utm_medium%3Dact%26gar%3DWzJd%26rapt%3DAEjHL4N5QBrof_buNP3iMRY2
        UKL0b1GKvXCIafuVtQ8npwXozqutwv6ua6UXTEDazKP3rDWRc-2HZ_VMnusKMANMKBJAmhEp6akWCN1nTXxdX_qOlcNpBbU
        %26authuser%3D2&pli=1&rapt=AEjHL4NkpLLX45-VWtRjwsj3OAg7I0-vUPKIJ7eRrTSETr0pAnE6BAGooF1I0YwCwiT4Hl25jmafW8OoK86jyS3w_uDRhwjYqN
        -yI_eA6hffwN27Bv9kBag)}`
    );

  // create
  fastify.post<{ Body: { email: string; type: "SIGNUP" | "RECOVER" } }>("/", async (request, reply) => {
    let session: ClientSession | null = null;

    try {
      const { email, type } = request.body;

      if (!email)
        return reply.code(400).send(JSONResponse("BAD_REQUEST", "email field is required on the request body"));

      switch (type) {
        case "SIGNUP": {
          if (await User.exists({ email })) return reply.code(409).send(JSONResponse("CONFLICT", "email already used"));

          break;
        }
        case "RECOVER": {
          if (!(await User.exists({ email })))
            return reply.code(409).send(JSONResponse("NOT_FOUND", "account does not exist"));
          break;
        }
      }

      session = await startSession();
      session.startTransaction();

      const transport = createTransport({
        service: "gmail",
        auth: {
          user: gmail_user,
          pass: gmail_password,
        },
      });

      const verify = await transport.verify();

      if (!verify) reply.code(500).send(JSONResponse("INTERNAL_SERVER_ERROR", "email transport verify failed"));

      const chars = "abcdefghijklmnopqrstuvwxyz1234567890";
      let random_string = "";

      for (let i = 0; i < 6; i++) {
        random_string += chars[Math.floor(Math.random() * chars.length)];
      }

      const otp = new OTP({
        email: email,
        type,
        pin: random_string.toUpperCase(),
      });
      await otp.save({ session });

      switch (type) {
        case "SIGNUP": {
          const html = await render(
            SignUpEmail({
              username: email.substring(0, email.indexOf("@")),
              code: random_string,
            })
          );

          await transport.sendMail({
            from: "croom.dev.noreply@gmail.com",
            to: email,
            subject: "Welcome to Croom your verification code is " + random_string.toLocaleUpperCase(),
            html,
          });

          break;
        }
        case "RECOVER": {
          if (await OTP.findOne({ email, type: "RECOVER" })) {
            await OTP.deleteMany({ email, type: "RECOVER" }, { session });
          }
          const html = await render(
            RecoverEmail({
              username: email.substring(0, email.indexOf("@")),
              code: random_string,
            })
          );

          await transport.sendMail({
            from: "croom.dev.noreply@gmail.com",
            to: email,
            subject:
              "An account recovery with this email is requested, here is the OTP to proceed teh request: " +
              random_string.toLocaleUpperCase(),
            html,
          });

          break;
        }
      }

      await session.commitTransaction();
      await session.endSession();

      return reply.code(201).send(JSONResponse("CREATED", "OTP verification code is sent"));
    } catch (error) {
      await session?.abortTransaction();
      fastify.log.error(error);
      return reply.code(500).send(JSONResponse("INTERNAL_SERVER_ERROR"));
    }
  });

  fastify.post<{ Body: { email: string; pin: string } }>("/check/recover", async (request, reply) => {
    try {
      const { email, pin } = request.body;

      if (!(await OTP.exists({ email, pin: pin.toUpperCase(), type: "RECOVER" })))
        return reply.code(404).send(JSONResponse("NOT_FOUND", "invalid pin"));

      return reply.code(200).send(JSONResponse("OK", "request successful"));
    } catch (error) {
      fastify.log.error(error);
      return reply.code(500).send(JSONResponse("INTERNAL_SERVER_ERROR"));
    }
  });

  done();
}
