name: Deploy to EC2

on:
  push:
    # paths:
    #   - "server/**"
    branches:
      - "wing"

jobs:
  deploy_to_ec2:
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Store Private key to a PEM file
        run: |-
          printf "%s" "${{secrets.PRIVATE_KEY}}" > chat-up.pem
          chmod 600 chat-up.pem

      - name: Push files to EC2 instance
        run: |
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' \
          -e  "ssh -i chat-up.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
          ./server ubuntu@${{secrets.EC2_INSTANCE}}:~/app

      - name: SSH to EC2 instance and restart server
        run: |
          ssh -i "chat-up.pem" -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_INSTANCE }} << "EOF"
            set -e   
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
           
            cd ~/app/server
            pnpm install --frozen-lockfile 
            pnpm install pm2 -g
           if ! pm2 restart chatup-server; then
             echo "PM2 restart failed. Checking logs..."
             pm2 logs chatup-server --lines 50
             exit 1
            fi
          EOF
