name: Deploy to EC2

on:
  push:
    paths:
      - "server/**"
    branches:
      - "main"

jobs:
  deploy_to_ec2:
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Store Private key to a PEM file
        run: |-
          printf "%s" "${{secrets.PRIVATE_KEY}}" > chat-up.pem
          chmod 600 chat-up.pem

      - name: Push files to EC2 instance
        run: |
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' --exclude "react-email" \
          -e  "ssh -i chat-up.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
          /server ubuntu@${{secrets.EC2_INSTANCE}}:~/app

      - name: SSH to EC2 instance and restart server
        run: |
          ssh -i "chat-up.pem" -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_INSTANCE }} << "EOF"
            
            echo "load NVM into the SSH connection"
            set -e   
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
           
            echo "go to server directory"
            cd ~/app

            echo "install all dependencies"
            pnpm install 
            
            echo "setup pnpm to enable global installment of dependencies"
            pnpm setup
            export PNPM_HOME=$(pnpm env get PNPM_HOME)
            export PATH="$PNPM_HOME:$PATH"

            echo "install pm2"
            pnpm add pm2 -g

            echo "save environment variables"
            printf "%s" "${{secrets.SERVER_ENV}}" > .env

            echo "build project"
            pnpm build
            
            echo "create session key"
            cd ./build
            npx --yes @fastify/secure-session > session-key

            echo "restart server"
            cd ..
            pm2 restart chatup-server --update-env || pm2 start pnpm --name "chatup-server" -- run start
          EOF
